// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  (function() {
    /*
      Revealing Pattern
    */

    var CommandManager, commander, runner, _ref, _ref1;
    (function() {}, (_ref = window.ƒ) != null ? _ref : window.ƒ = {}, (_ref1 = ƒ.Utils) != null ? _ref1 : ƒ.Utils = {}, ƒ.App = (function() {
      var init;
      return init = function() {
        return ƒ.Utils.log('App init...');
      };
    })())(jQuery);
    /*
      Commander Pattern
    */

    commander = (function() {
      var c1, c2, cmmds, pv1;
      pv1 = 0;
      c1 = function() {
        return pv1 = "Command 1";
      };
      c2 = function() {
        return pv1 = "Command 2";
      };
      return cmmds = {
        command1: c1,
        command2: c2,
        value: function() {
          return pv1;
        }
      };
    })();
    CommandManager = (function() {

      function CommandManager() {
        var cmmds;
        cmmds = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.cmmds = cmmds;
      }

      CommandManager.prototype.run = function() {
        var command, _i, _len, _ref2, _results;
        _ref2 = this.cmmds;
        _results = [];
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          command = _ref2[_i];
          _results.push(command());
        }
        return _results;
      };

      return CommandManager;

    })();
    runner = new CommandManager(commander.command1, commander.command2);
    runner.run();
    return commander.value();
  })();

}).call(this);
