// Generated by CoffeeScript 1.3.3
(function() {
  var _ref;

  if ((_ref = window.nerds) == null) {
    window.nerds = {};
  }

  nerds.init = function() {
    nerds.anchors_scroll();
    nerds.anchors_external();
    return nerds.lastfm_recent_tracks();
  };

  nerds.lastfm_recent_tracks = function() {
    return $.ajax('__/recent-tracks/', {
      type: 'GET',
      dataType: 'json',
      error: function(jqXHR, textStatus, errorThrown) {
        var body$;
        body$ = $("body");
        return body$.append("err: " + textStatus);
      },
      success: function(data, textStatus, jqXHR) {
        var lastfm_recent_tracks$, t, title_content, _i, _len;
        lastfm_recent_tracks$ = $('#lastfm_recent_tracks');
        title_content = '';
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          t = data[_i];
          title_content += t + "\n\n";
        }
        return lastfm_recent_tracks$.prop('title', "" + title_content);
      }
    });
  };

  nerds.anchors_scroll = function() {
    return $('a[href^="#"]').click(function(e) {
      var $el, $target, el, href, scope, target;
      el = this;
      $el = $(el);
      href = $el.prop('href');
      target = href.split('/')[href.split('/').length - 1];
      $target = $(target);
      scope = 'html,body';
      $(scope).animate({
        'scrollTop': ($target.offset().top)
      }, 750, 'swing', function() {});
      return e.preventDefault();
    });
  };

  nerds.anchors_external = function() {
    return $('a[rel="external"]').click(function(e) {
      var $el, el;
      el = this;
      $el = $(el);
      window.open($el.prop('href'), $el.prop('title'));
      return e.preventDefault();
    });
  };

  $(document).ready(function() {
    return nerds.init();
  });

}).call(this);
